# Auto-generated from descriptors/library-templates.json
# Do not edit this file directly - run codegen instead
"""
Library template metadata for Nia Universal HTML generation.
This module provides template information for bot tool prompts.
"""
from .templates import (
    LIBRARY_TEMPLATES,
    LIBRARY_TYPES,
    get_template_by_id,
    get_templates_by_type,
    build_prompt_guidance,
)

__all__ = [
    'LIBRARY_TEMPLATES',
    'LIBRARY_TYPES',
    'get_template_by_id',
    'get_templates_by_type',
    'build_prompt_guidance',
]
