apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: heartbeat-staging
  namespace: flux-system
spec:
  interval: 1h
  approvePlan: "auto"
  path: ./infra/terraform/modules/synthetics-canary
  sourceRef:
    kind: GitRepository
    name: infra-repo
    namespace: flux-system
  serviceAccountName: tf-runner
  runnerPodTemplate:
    spec:
      env:
        - name: AWS_REGION
          value: "us-east-2"
  vars:
    - name: canary_name
      value: "api-heartbeat-staging"
    - name: targets
      value: ["https://interface.stg.nxops.net/health", "https://interface.stg.nxops.net/health/deep"]
    - name: schedule_expression
      value: "rate(5 minutes)"
