"""Utilities to transparently observe Pipecat flow summaries.

This module installs a lightweight tap that records metadata about
conversation summaries generated by the Pipecat ``FlowManager`` when the
``RESET_WITH_SUMMARY`` context strategy is used. The tap is intentionally
non-intrusive: it never mutates the frames queued by the manager or
changes the control-flow decisions. Instead, it collects diagnostic
information so the rest of the bot can access the most recent summary
text and its formatted frame payload.
"""

from __future__ import annotations

import copy
import time
from functools import wraps
from typing import Any, Dict, Optional

from pipecat_flows.manager import FlowManager
from bot.loguru import get_logger

logger = get_logger(__name__, tag="summary-tap")

_MAX_HISTORY = 25


def _get_state_dict(flow_manager: Any) -> Optional[Dict[str, Any]]:
    """Safely resolve the state dictionary for a flow manager instance."""

    state = getattr(flow_manager, "state", None)
    if isinstance(state, dict):
        return state

    # Fall back to private attribute access for defensive compatibility.
    private_state = getattr(flow_manager, "_state", None)
    if isinstance(private_state, dict):
        return private_state

    return None


def _ensure_tap_state(state: Dict[str, Any]) -> Dict[str, Any]:
    tap_state = state.setdefault("_summary_tap", {})
    tap_state.setdefault("history", [])
    tap_state.setdefault("version", 0)
    return tap_state


def _record_summary_metadata(
    flow_manager: Any,
    summary_text: str,
    formatted_message: Optional[Dict[str, Any]] = None,
) -> Optional[Dict[str, Any]]:
    """Capture summary metadata on the flow manager state.

    The recorded entry can be retrieved via :func:`get_last_summary`.
    Returns the entry that was stored, or ``None`` if the state dictionary
    is unavailable.
    """

    state = _get_state_dict(flow_manager)
    if state is None:
        logger.debug("[summary-tap] Flow manager state unavailable; cannot record summary")
        return None

    tap_state = _ensure_tap_state(state)
    version = int(tap_state.get("version", 0)) + 1

    entry: Dict[str, Any] = {
        "summary_text": summary_text,
        "formatted_message": copy.deepcopy(formatted_message)
        if formatted_message is not None
        else None,
        "timestamp": time.time(),
        "node": getattr(flow_manager, "current_node", None),
        "version": version,
    }

    tap_state["version"] = version
    tap_state["last_summary"] = copy.deepcopy(entry)

    history = tap_state.setdefault("history", [])
    history.append(copy.deepcopy(entry))
    if len(history) > _MAX_HISTORY:
        del history[:-_MAX_HISTORY]

    logger.debug(
        "[summary-tap] Recorded summary version=%s node=%s" % (version, entry["node"])
    )
    return entry


def install_summary_tap() -> None:
    """Install the tap on :class:`FlowManager` if it is not present."""

    if getattr(FlowManager, "_summary_tap_installed", False):
        return

    original = FlowManager._create_conversation_summary

    @wraps(original)
    async def _wrapped(self: FlowManager, summary_prompt, context):
        summary = await original(self, summary_prompt, context)

        if summary:
            formatted_message = None
            try:
                formatted_message = self._adapter.format_summary_message(summary)  # type: ignore[attr-defined]
            except Exception:  # pragma: no cover - defensive logging
                logger.exception("[summary-tap] Failed to format summary message")

            try:
                _record_summary_metadata(self, summary, formatted_message)
            except Exception:  # pragma: no cover - defensive logging
                logger.exception("[summary-tap] Failed to record summary metadata")

        return summary

    FlowManager._create_conversation_summary = _wrapped  # type: ignore[method-assign]
    FlowManager._summary_tap_installed = True  # type: ignore[attr-defined]
    logger.debug("[summary-tap] Installed FlowManager summary tap")


def get_last_summary(flow_manager: Any) -> Optional[Dict[str, Any]]:
    """Return the most recent summary metadata for ``flow_manager``."""

    state = _get_state_dict(flow_manager)
    if state is None:
        return None

    tap_state = state.get("_summary_tap")
    if not isinstance(tap_state, dict):
        return None

    last_summary = tap_state.get("last_summary")
    if isinstance(last_summary, dict):
        return copy.deepcopy(last_summary)
    return None


def get_summary_version(flow_manager: Any) -> int:
    """Return the latest recorded summary version for ``flow_manager``."""

    state = _get_state_dict(flow_manager)
    if state is None:
        return 0

    tap_state = state.get("_summary_tap")
    if not isinstance(tap_state, dict):
        return 0

    version = tap_state.get("version")
    return int(version) if isinstance(version, int) else 0


__all__ = [
    "install_summary_tap",
    "get_last_summary",
    "get_summary_version",
]

# Re-export helper for testing via ``from flows.summary_tap import _record_summary_metadata``.
__all__.append("_record_summary_metadata")
