'use client';

import React from 'react';
import { HtmlContentViewer, useHtmlContentViewer } from '@interface/features/HtmlGeneration/components/HtmlContentViewer';

// Example integration component - shows how to use the HTML content viewer (relocated into feature/examples)
export function HtmlContentIntegrationExample() {
  const { content, isFullscreen, showContent, closeContent, toggleFullscreen } = useHtmlContentViewer();

  const handleCreateContent = (contentType: 'game' | 'app' | 'tool' | 'interactive') => {
    const examples: Record<string, any> = {
      game: {
        title: 'Snake Game',
        type: 'game',
        js: "window.logger?.info('snake game placeholder');",
        html: '<html><body><h1>Snake Game Placeholder</h1></body></html>'
      },
      app: {
        title: 'Task Manager',
        type: 'app',
        html: '<html><body><h1>Task Manager Placeholder</h1></body></html>'
      },
      tool: {
        title: 'Drawing Tool',
        type: 'tool',
        html: '<html><body><h1>Drawing Tool Placeholder</h1></body></html>'
      },
      interactive: {
        title: 'Quiz App',
        type: 'interactive',
        html: '<html><body><h1>Quiz App Placeholder</h1></body></html>'
      }
    };
    const example = examples[contentType];
    showContent(example);
  };

  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold mb-4">HTML Content Creation Demo</h2>
      <p className="text-gray-600 mb-6">Demonstrates how HTML content generated by the platform is displayed inside the viewer.</p>
      <div className="flex gap-4 mb-6">
        {(['game','app','tool','interactive'] as const).map(k => (
          <button key={k} onClick={() => handleCreateContent(k)} className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 capitalize">
            Create {k}
          </button>
        ))}
      </div>
      {content && (
        <HtmlContentViewer
          // title={content.title}
          htmlContent={content.html}
          contentType={content.type}
          cssContent={content.css}
          jsContent={content.js}
          onClose={closeContent}
          isFullscreen={isFullscreen}
          onToggleFullscreen={toggleFullscreen}
        />
      )}
      {!content && <div className="text-center text-gray-500 py-8">Select a type to generate demo content.</div>}
    </div>
  );
}

export default HtmlContentIntegrationExample;
