apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/base/operators/tf-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
