import type { LibraryTemplateDescriptor } from './library-templates';
import { buildStorageBootstrapSnippet } from './storage-library.template';

const STORAGE_BOOTSTRAP = buildStorageBootstrapSnippet();

export const counterWidgetTemplate: LibraryTemplateDescriptor = {
  id: 'counter_widget_v1',
  libraryType: 'tool',
  name: 'Counter Widget Starter',
  filename: 'counter-widget.html',
  description: 'Simple animated counter with increment/decrement, reset, and persistence hooks.',
  tags: ['counter', 'widget', 'persisted'],
  content: [
    STORAGE_BOOTSTRAP,
    '<div class="counter-card">',
    '  <div class="label">Counter</div>',
    '  <div class="value" id="counterValue">0</div>',
    '  <div class="controls">',
    '    <button data-delta="-1">-1</button>',
    '    <button data-delta="1">+1</button>',
    '    <button id="resetCounter" class="ghost">Reset</button>',
    '  </div>',
    '</div>',
    '<style>',
    '  .counter-card { max-width: 320px; margin: 24px auto; padding: 18px; border-radius: 16px; background: linear-gradient(135deg, #101928, #0f223d); color: #eaf2ff; font-family: "Inter", system-ui, -apple-system, sans-serif; box-shadow: 0 14px 32px rgba(0,0,0,0.35); text-align: center; }',
    '  .label { font-size: 14px; opacity: 0.8; letter-spacing: 0.02em; }',
    '  .value { font-size: 64px; font-weight: 800; margin: 12px 0; text-shadow: 0 8px 20px rgba(0,0,0,0.35); }',
    '  .controls { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-top: 12px; }',
    '  button { padding: 12px; border: none; border-radius: 12px; background: #2f8bff; color: #fff; font-weight: 700; cursor: pointer; transition: transform 120ms ease, box-shadow 120ms ease; }',
    '  button:hover { transform: translateY(-1px); box-shadow: 0 10px 24px rgba(47,139,255,0.3); }',
    '  button.ghost { background: rgba(255,255,255,0.08); color: #eaf2ff; }',
    '</style>',
    '<script>',
    '  window.counterState = { value: 0, _id: null };',
    '  window.renderCounter = function renderCounter() {',
    "    document.getElementById('counterValue').textContent = window.counterState.value.toString();",
    '  };',
    '  window.persistCounter = async function persistCounter() {',
    "    if (!window.api?.saveData || !window.api?.updateData) return;",
    '    try {',
    '      const payload = { key: "counter_widget", state: { value: window.counterState.value } };',
    '      if (window.counterState._id) {',
    '        await window.api.updateData(window.counterState._id, payload);',
    '      } else {',
    '        const saved = await window.api.saveData(payload);',
    '        window.counterState._id = saved?._id || null;',
    '      }',
    '    } catch (err) { console.warn("Counter persist failed", err); }',
    '  };',
    '  window.adjustCounter = async function adjustCounter(delta) {',
    '    window.counterState.value = Math.max(0, window.counterState.value + delta);',
    '    window.renderCounter();',
    '    await window.persistCounter();',
    '  };',
    '  window.resetCounter = async function resetCounter() { window.counterState.value = 0; window.renderCounter(); await window.persistCounter(); };',
    '  window.loadCounter = async function loadCounter() {',
    "    if (!window.api?.listData) { window.renderCounter(); return; }",
    '    try {',
    '      const items = await window.api.listData({ key: "counter_widget" });',
    '      const first = Array.isArray(items) ? items[0] : null;',
    '      if (first?.data?.state?.value !== undefined) {',
    '        window.counterState.value = Number(first.data.state.value) || 0;',
    '        window.counterState._id = first._id || null;',
    '      }',
    '    } catch (err) { console.warn("Counter load failed", err); }',
    '    window.renderCounter();',
    '  };',
    "  document.addEventListener('DOMContentLoaded', () => {",
    "    document.querySelectorAll('button[data-delta]').forEach(btn => btn.addEventListener('click', (e) => window.adjustCounter(Number(e.target.dataset.delta))));",
    "    document.getElementById('resetCounter')?.addEventListener('click', window.resetCounter);",
    '    window.loadCounter();',
    '  });',
    '</script>'
  ].join('\n')
};
