import type { LibraryTemplateDescriptor } from './library-templates';
import { buildStorageBootstrapSnippet } from './storage-library.template';

const STORAGE_BOOTSTRAP = buildStorageBootstrapSnippet();

export const partyPackEmojiVoteTemplate: LibraryTemplateDescriptor = {
  id: 'party_pack_poll',
  libraryType: 'interactive',
  name: 'Party Pack: Emoji Vote',
  filename: 'party-pack-emoji-vote.html',
  description: 'Emoji-based quick vote with live tally and persistence.',
  tags: ['poll', 'emoji', 'fun', 'persisted'],
  content: [
    STORAGE_BOOTSTRAP,
    '<div class="vote-card">',
    '  <div class="title">Emoji Vote</div>',
    '  <div class="choices">',
    "    <button data-choice='🔥'>🔥 Fire</button>",
    "    <button data-choice='🌊'>🌊 Wave</button>",
    "    <button data-choice='🌟'>🌟 Star</button>",
    '  </div>',
    '  <div id="results" class="results"></div>',
    '  <button id="resetVotes" class="reset">Reset Votes</button>',
    '</div>',
    '<style>',
    '  .vote-card { max-width: 360px; margin: 20px auto; padding: 16px; border-radius: 14px; background: linear-gradient(135deg, #14161c, #0f1f3a); color: #e8f0ff; font-family: "Inter", system-ui, -apple-system, sans-serif; box-shadow: 0 12px 28px rgba(0,0,0,0.32); }',
    '  .title { font-weight: 700; margin-bottom: 10px; }',
    '  .choices { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }',
    '  .choices button { padding: 12px 0; font-size: 20px; border: none; border-radius: 12px; background: rgba(255,255,255,0.06); color: #fff; cursor: pointer; }',
    '  .results { margin-top: 12px; font-size: 14px; min-height: 20px; }',
    '  .reset { margin-top: 12px; width: 100%; padding: 10px; border: none; border-radius: 10px; background: #ff7aa2; color: #fff; font-weight: 700; cursor: pointer; }',
    '</style>',
    '<script>',
    '  const partySession = { id: null, name: null };',
    '  function refreshPartySession(cfg) {',
    "    const config = cfg || (typeof window.getAppletConfig === 'function' && window.getAppletConfig()) || null;",
    '    if (!config) return;',
    '    partySession.id = config.userId || config.id || null;',
    '    partySession.name = config.userName || config.name || null;',
    '    if (partySession.id) window.userId = partySession.id; // legacy compatibility',
    '  }',
    '  window.partyVotes = { map: {}, voters: {}, _id: null };',
    '  function recomputeEmojiCounts() {',
    '    const counts = {};',
    '    Object.entries(window.partyVotes.voters || {}).forEach(([, choice]) => {',
    '      counts[choice] = (counts[choice] || 0) + 1;',
    '    });',
    '    window.partyVotes.map = counts;',
    '  }',
    '  window.renderVotes = function renderVotes() {',
    "    const container = document.getElementById('results');",
    '    const entries = Object.entries(window.partyVotes.map);',
    '    if (!entries.length) { container.textContent = "No votes yet"; return; }',
    '    container.innerHTML = entries.map(([emoji, count]) => `${emoji}: ${count}`).join(" | ");',
    '  };',
    '  window.persistVotes = async function persistVotes() {',
    "    if (!window.api?.saveData || !window.api?.updateData) return;",
    '    try {',
    '      const payload = { key: "party_pack_emoji_vote", state: { votes: window.partyVotes.map, voters: window.partyVotes.voters } };',
    '      if (window.partyVotes._id) {',
    '        await window.api.updateData(window.partyVotes._id, payload);',
    '      } else {',
    '        const saved = await window.api.saveData(payload);',
    '        window.partyVotes._id = saved?._id || null;',
    '      }',
    '    } catch (err) { console.warn("Votes persist failed", err); }',
    '  };',
    '  window.handleVote = async function handleVote(choice) {',
    '    const userId = partySession.id || window.userId || null;',
    '    if (!userId) { alert("Sign in to vote."); return; }',
    '    const prev = window.partyVotes.voters[userId];',
    '    if (prev === choice) { alert("You already picked " + choice + "."); return; }',
    '    if (prev) { window.partyVotes.map[prev] = Math.max(0, (window.partyVotes.map[prev] || 0) - 1); }',
    '    window.partyVotes.voters[userId] = choice;',
    '    window.partyVotes.map[choice] = (window.partyVotes.map[choice] || 0) + 1;',
    '    window.renderVotes();',
    '    await window.persistVotes();',
    '  };',
    '  window.resetVotes = async function resetVotes() { window.partyVotes.map = {}; window.partyVotes.voters = {}; window.renderVotes(); await window.persistVotes(); };',
    '  window.loadVotes = async function loadVotes() {',
    "    if (!window.api?.listData) { window.renderVotes(); return; }",
    '    try {',
    '      const items = await window.api.listData({ key: "party_pack_emoji_vote" });',
    '      const first = Array.isArray(items) ? items[0] : null;',
    '      if (first?.data?.state) {',
    '        window.partyVotes.voters = first.data.state.voters || {};',
    '        window.partyVotes.map = first.data.state.votes || {};',
    '        window.partyVotes._id = first._id || null;',
    '        if (Object.keys(window.partyVotes.voters).length) { recomputeEmojiCounts(); }',
    '      }',
    '    } catch (err) { console.warn("Votes load failed", err); }',
    '    window.renderVotes();',
    '  };',
    "  document.addEventListener('DOMContentLoaded', () => {",
    '    refreshPartySession();',
    "    document.querySelectorAll('.choices button').forEach(btn => btn.addEventListener('click', (e) => window.handleVote(e.target.dataset.choice)));",
    "    document.getElementById('resetVotes')?.addEventListener('click', window.resetVotes);",
    '    window.addEventListener("appletConfigReady", (e) => refreshPartySession(e.detail));',
    '    window.loadVotes();',
    '  });',
    '</script>'
  ].join('\n')
};
