import type { LibraryTemplateDescriptor } from './library-templates';
import { buildStorageBootstrapSnippet } from './storage-library.template';

const STORAGE_BOOTSTRAP = buildStorageBootstrapSnippet();

export const partyPackScoreKeeperTemplate: LibraryTemplateDescriptor = {
  id: 'party_pack_score',
  libraryType: 'interactive',
  name: 'Party Pack: Score Keeper',
  filename: 'party-pack-score-keeper.html',
  description: 'Host-managed scoreboard with per-player tracking.',
  tags: ['score', 'game', 'party', 'persisted'],
  content: [
    STORAGE_BOOTSTRAP,
    '<div class="score-card">',
    '  <div class="title">🎯 Score Keeper</div>',
    '  <ul id="scores"></ul>',
    '  <div class="actions">',
    "    <input id='playerName' placeholder='Player Name' />",
    '    <button id="addPlayer">Add</button>',
    '    <button id="resetScores" class="reset">Reset</button>',
    '  </div>',
    '</div>',
    '<style>',
    '  .score-card { max-width: 360px; margin: 20px auto; padding: 16px; border-radius: 14px; background: linear-gradient(135deg, #14161c, #0f1f3a); color: #e8f0ff; font-family: "Inter", system-ui, -apple-system, sans-serif; box-shadow: 0 12px 28px rgba(0,0,0,0.32); }',
    '  .title { font-weight: 700; margin-bottom: 10px; }',
    '  #scores { list-style: none; padding: 0; margin: 0 0 10px; }',
    '  #scores li { display: flex; justify-content: space-between; align-items: center; padding: 6px 8px; background: rgba(255,255,255,0.04); margin-bottom: 6px; border-radius: 8px; }',
    '  .score-controls button { padding: 4px 8px; margin-left: 4px; border: none; border-radius: 6px; background: #00c896; color: #000; font-weight: 600; cursor: pointer; }',
    '  .actions { display: flex; gap: 6px; }',
    '  .actions input { flex: 1; padding: 8px; border-radius: 8px; border: none; }',
    '  .actions button { padding: 8px 14px; border: none; border-radius: 8px; background: #00d9a6; color: #000; font-weight: 700; cursor: pointer; }',
    '  .reset { background: #ff7aa2 !important; color: #fff !important; }',
    '</style>',
    '<script>',
    '  window.scoreData = { players: {}, _id: null };',
    '  window.renderScores = function renderScores() {',
    "    const ul = document.getElementById('scores');",
    '    ul.innerHTML = "";',
    '    Object.entries(window.scoreData.players).sort((a, b) => b[1] - a[1]).forEach(([name, score]) => {',
    '      const li = document.createElement("li");',
    '      li.innerHTML = `<span>${name}: <strong>${score}</strong></span>',
    '        <span class="score-controls">',
    '          <button onclick="window.adjustScore(\'${name}\', 1)">+</button>',
    '          <button onclick="window.adjustScore(\'${name}\', -1)">−</button>',
    '          <button onclick="window.removePlayer(\'${name}\')">×</button>',
    '        </span>`;',
    '      ul.appendChild(li);',
    '    });',
    '  };',
    '  window.persistScores = async function persistScores() {',
    "    if (!window.api?.saveData || !window.api?.updateData) return;",
    '    try {',
    '      const payload = { key: "party_pack_score_keeper", state: { players: window.scoreData.players } };',
    '      if (window.scoreData._id) {',
    '        await window.api.updateData(window.scoreData._id, payload);',
    '      } else {',
    '        const saved = await window.api.saveData(payload);',
    '        window.scoreData._id = saved?._id || null;',
    '      }',
    '    } catch (err) { console.warn("Score persist failed", err); }',
    '  };',
    '  window.addPlayer = async function addPlayer() {',
    "    const input = document.getElementById('playerName');",
    '    const name = input.value.trim();',
    '    if (!name || window.scoreData.players[name] !== undefined) return;',
    '    window.scoreData.players[name] = 0;',
    '    input.value = "";',
    '    window.renderScores();',
    '    await window.persistScores();',
    '  };',
    '  window.adjustScore = async function adjustScore(name, delta) {',
    '    if (window.scoreData.players[name] === undefined) return;',
    '    window.scoreData.players[name] += delta;',
    '    window.renderScores();',
    '    await window.persistScores();',
    '  };',
    '  window.removePlayer = async function removePlayer(name) {',
    '    delete window.scoreData.players[name];',
    '    window.renderScores();',
    '    await window.persistScores();',
    '  };',
    '  window.resetScores = async function resetScores() {',
    '    window.scoreData.players = {};',
    '    window.renderScores();',
    '    await window.persistScores();',
    '  };',
    '  window.loadScores = async function loadScores() {',
    "    if (!window.api?.listData) { window.renderScores(); return; }",
    '    try {',
    '      const items = await window.api.listData({ key: "party_pack_score_keeper" });',
    '      const first = Array.isArray(items) ? items[0] : null;',
    '      if (first?.data?.state?.players) {',
    '        window.scoreData.players = first.data.state.players;',
    '        window.scoreData._id = first._id || null;',
    '      }',
    '    } catch (err) { console.warn("Score load failed", err); }',
    '    window.renderScores();',
    '  };',
    "  document.addEventListener('DOMContentLoaded', () => {",
    "    document.getElementById('addPlayer')?.addEventListener('click', window.addPlayer);",
    "    document.getElementById('resetScores')?.addEventListener('click', window.resetScores);",
    '    window.loadScores();',
    '  });',
    '</script>'
  ].join('\n')
};
