import type { LibraryTemplateDescriptor } from './library-templates';
import { buildStorageBootstrapSnippet } from './storage-library.template';

const STORAGE_BOOTSTRAP = buildStorageBootstrapSnippet();

export const quickPollTemplate: LibraryTemplateDescriptor = {
  id: 'quick_poll_v1',
  libraryType: 'interactive',
  name: 'Quick Poll (Two Option)',
  filename: 'quick-poll.html',
  description: 'Two-option poll with percentages and persistence.',
  tags: ['poll', 'vote', 'persisted'],
  content: [
    STORAGE_BOOTSTRAP,
    '<div class="poll-card">',
    '  <div class="question" id="pollQuestion">Which option wins?</div>',
    '  <div class="options">',
    '    <button class="option" data-option="A">Option A</button>',
    '    <button class="option" data-option="B">Option B</button>',
    '  </div>',
    '  <div class="results">',
    '    <div class="row"><span>A votes:</span><span id="votesA">0</span></div>',
    '    <div class="row"><span>B votes:</span><span id="votesB">0</span></div>',
    '    <div class="row"><span>Totals:</span><span id="totalVotes">0</span></div>',
    '    <div class="bar">',
    '      <div id="barA" class="bar-fill a"></div>',
    '      <div id="barB" class="bar-fill b"></div>',
    '    </div>',
    '  </div>',
    '  <div class="controls">',
    '    <input id="questionInput" placeholder="Edit question" />',
    '    <button id="resetPoll">Reset Poll</button>',
    '  </div>',
    '</div>',
    '<style>',
    '  .poll-card { max-width: 420px; margin: 24px auto; padding: 18px; border-radius: 16px; background: linear-gradient(135deg, #0c1525, #0f1f3a); color: #e8f0ff; box-shadow: 0 12px 30px rgba(0,0,0,0.3); font-family: "Inter", system-ui, -apple-system, sans-serif; }',
    '  .question { font-weight: 700; font-size: 18px; margin-bottom: 12px; }',
    '  .options { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin-bottom: 12px; }',
    '  .option { padding: 12px; border-radius: 12px; border: none; background: #1f84ff; color: #fff; font-weight: 700; cursor: pointer; transition: transform 120ms ease, box-shadow 120ms ease; }',
    '  .option:hover { transform: translateY(-1px); box-shadow: 0 8px 20px rgba(31,132,255,0.3); }',
    '  .results { background: rgba(255,255,255,0.04); border-radius: 12px; padding: 12px; margin-bottom: 12px; }',
    '  .row { display: flex; justify-content: space-between; padding: 4px 0; font-size: 14px; }',
    '  .bar { position: relative; height: 12px; background: rgba(255,255,255,0.1); border-radius: 999px; overflow: hidden; margin-top: 6px; display: grid; grid-template-columns: 1fr 1fr; }',
    '  .bar-fill { height: 100%; transition: width 160ms ease; }',
    '  .bar-fill.a { background: linear-gradient(90deg, #7fd2ff, #4da3ff); }',
    '  .bar-fill.b { background: linear-gradient(90deg, #f7b8ff, #d96bff); }',
    '  .controls { display: grid; grid-template-columns: 1fr auto; gap: 10px; }',
    '  input { padding: 10px 12px; border-radius: 10px; border: 1px solid rgba(255,255,255,0.12); background: rgba(255,255,255,0.06); color: #e8f0ff; }',
    '  button#resetPoll { background: #ff5c8d; color: #fff; border: none; border-radius: 10px; padding: 10px 12px; font-weight: 700; cursor: pointer; }',
    '</style>',
    '<script>',
    '  const pollSession = { id: null, name: null };',
    '  function refreshPollSession(cfg) {',
    "    const config = cfg || (typeof window.getAppletConfig === 'function' && window.getAppletConfig()) || null;",
    '    if (!config) return;',
    '    pollSession.id = config.userId || config.id || null;',
    '    pollSession.name = config.userName || config.name || null;',
    '    if (pollSession.id) window.userId = pollSession.id; // legacy compatibility',
    '  }',
    '  window.pollState = { a: 0, b: 0, question: "Which option wins?", voters: {}, _id: null };',
    '  function recomputeCountsFromVoters() {',
    '    const counts = { A: 0, B: 0 };',
    '    Object.values(window.pollState.voters || {}).forEach(v => { if (v === "A") counts.A += 1; if (v === "B") counts.B += 1; });',
    '    window.pollState.a = counts.A;',
    '    window.pollState.b = counts.B;',
    '  }',
    '  window.renderPoll = function renderPoll() {',
    "    const total = window.pollState.a + window.pollState.b;",
    "    document.getElementById('pollQuestion').textContent = window.pollState.question;",
    "    document.getElementById('votesA').textContent = window.pollState.a.toString();",
    "    document.getElementById('votesB').textContent = window.pollState.b.toString();",
    "    document.getElementById('totalVotes').textContent = total.toString();",
    "    const aPct = total ? Math.round((window.pollState.a / total) * 100) : 0;",
    "    const bPct = total ? 100 - aPct : 0;",
    "    document.getElementById('barA').style.width = aPct + '%';",
    "    document.getElementById('barB').style.width = bPct + '%';",
    '  };',
    '  window.persistPoll = async function persistPoll() {',
    "    if (!window.api?.saveData || !window.api?.updateData) return;",
    '    try {',
    '      const payload = { key: "quick_poll", state: { a: window.pollState.a, b: window.pollState.b, question: window.pollState.question, voters: window.pollState.voters } };',
    '      if (window.pollState._id) {',
    '        await window.api.updateData(window.pollState._id, payload);',
    '      } else {',
    '        const saved = await window.api.saveData(payload);',
    '        window.pollState._id = saved?._id || null;',
    '      }',
    '    } catch (err) { console.warn("Poll persist failed", err); }',
    '  };',
    '  window.castVote = async function castVote(option) {',
    '    const userId = pollSession.id || window.userId || null;',
    '    if (!userId) { alert("Sign in to vote."); return; }',
    '    const prev = window.pollState.voters[userId];',
    '    if (prev === option) { alert("You already voted for " + option + "."); return; }',
    '    if (prev === "A") window.pollState.a = Math.max(0, window.pollState.a - 1);',
    '    if (prev === "B") window.pollState.b = Math.max(0, window.pollState.b - 1);',
    '    if (option === "A") window.pollState.a += 1; else if (option === "B") window.pollState.b += 1; else { return; }',
    '    window.pollState.voters[userId] = option;',
    '    window.renderPoll();',
    '    await window.persistPoll();',
    '  };',
    '  window.resetPoll = async function resetPoll() { window.pollState = { a: 0, b: 0, question: window.pollState.question, voters: {}, _id: window.pollState._id }; window.renderPoll(); await window.persistPoll(); };',
    '  window.updateQuestion = async function updateQuestion(evt) { window.pollState.question = evt.target.value || "Which option wins?"; window.renderPoll(); await window.persistPoll(); };',
    '  window.loadPoll = async function loadPoll() {',
    "    if (!window.api?.listData) { window.renderPoll(); return; }",
    '    try {',
    '      const items = await window.api.listData({ key: "quick_poll" });',
    '      const first = Array.isArray(items) ? items[0] : null;',
    '      if (first?.data?.state) {',
    '        window.pollState.question = first.data.state.question || window.pollState.question;',
    '        window.pollState.voters = first.data.state.voters || {};',
    '        window.pollState._id = first._id || null;',
    '        recomputeCountsFromVoters();',
    '        const storedA = Number(first?.data?.state?.a);',
    '        const storedB = Number(first?.data?.state?.b);',
    '        if (Number.isFinite(storedA) && Number.isFinite(storedB) && (storedA || storedB) && !Object.keys(window.pollState.voters).length) {',
    '          window.pollState.a = storedA;',
    '          window.pollState.b = storedB;',
    '        }',
    '      }',
    '    } catch (err) { console.warn("Poll load failed", err); }',
    '    window.renderPoll();',
    '  };',
    "  document.addEventListener('DOMContentLoaded', () => {",
    '    refreshPollSession();',
    "    document.querySelectorAll('.option').forEach(btn => btn.addEventListener('click', (e) => window.castVote(e.target.dataset.option)));",
    "    document.getElementById('resetPoll')?.addEventListener('click', window.resetPoll);",
    "    document.getElementById('questionInput')?.addEventListener('input', window.updateQuestion);",
    '    window.addEventListener("appletConfigReady", (e) => { refreshPollSession(e.detail); });',
    '    window.loadPoll();',
    '  });',
    '</script>'
  ].join('\n')
};
